# Generated by Django 5.0.4 on 2024-05-14 15:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Команда')),
                ('creation_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Год создания')),
                ('sport', models.CharField(choices=[('FB', 'Футбол'), ('BS', 'Баскетбол'), ('HK', 'Хоккей'), ('BB', 'Бейсбол'), ('VL', 'Волейбол')], max_length=2, verbose_name='Вид спорта')),
                ('coach', models.CharField(max_length=100, verbose_name='Тренер')),
                ('owner', models.CharField(max_length=100, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('l_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('shirt_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Номер')),
                ('height', models.FloatField(verbose_name='Рост')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
    ]
